name: recipe_browser
description: "Your recipe app"
publish_to: 'none'

version: 1.0.0+1

environment:
  sdk: ^3.6.0

dependencies:
  flutter:
    sdk: flutter
  cupertino_icons: ^1.0.8
  # navigation
  go_router: ^15.1.1
  url_strategy: ^0.3.0
  # storage
  shared_preferences: ^2.5.3
  drift: ^2.26.1
  drift_flutter: ^0.2.4
  json_annotation: ^4.9.0
  path_provider: ^2.1.5
  # state
  provider: ^6.1.5
  bloc: ^9.0.0
  flutter_bloc: ^9.1.1
  #utils
  equatable: ^2.0.7
  uuid: ^4.5.1
  # theme
  flex_color_scheme: ^8.2.0
  # ui
  skeletonizer: ^1.4.3
  smooth_sheets: ^0.11.5
  flutter_dismissible_tile: ^1.1.0

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^5.0.0
  # native
  flutter_launcher_icons: ^0.14.3
  flutter_native_splash: ^2.4.6
  rename: ^3.1.0
  # storage
  drift_dev: ^2.26.1
  json_serializable: ^6.9.5
  # builder
  build_runner: ^2.4.15

flutter:
  uses-material-design: true

  assets:
    - assets/not_found/not_found_desktop.png
    - assets/not_found/not_found_tablet.png
    - assets/not_found/not_found_mobile.png
    - assets/placeholder/recipe_placeholder.jpg

  # fonts:
  #   - family: Schyler
  #     fonts:
  #       - asset: fonts/Schyler-Regular.ttf
  #       - asset: fonts/Schyler-Italic.ttf
  #         style: italic
  #   - family: Trajan Pro
  #     fonts:
  #       - asset: fonts/TrajanPro.ttf
  #       - asset: fonts/TrajanPro_Bold.ttf
  #         weight: 700
